### S3 T01: Exercicis de programació numèrica

- Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.


In [4]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2],[3,5],[7,2]])

def statisticArr (arr):

    if arr.ndim > 1:
            print("Error: The array should be only one dimension")
    else:
    
        print("The total count is:", len(arr))
        print("The mean valor is:", arr.mean())
        print("The median valor is:", np.median(arr))
        print("The desviation standard ist:", np.std(arr).round(4))
        print("The minimum valor is:", arr.min())
        print("The maximum valor is:", arr.max())
        print("Q 25:",np.percentile(arr,25))

statisticArr(arr1)
statisticArr(arr2)

The total count is: 5
The mean valor is: 3.0
The median valor is: 3.0
The desviation standard ist: 1.4142
The minimum valor is: 1
The maximum valor is: 5
Q 25: 2.0
Error: The array should be only one dimension



- Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.


In [3]:
def squareNN(n):
    print( np.random.randint(101,size=(n,n)))

squareNN(3)
squareNN(6)


[[66 16 57]
 [25 65 94]
 [30  0 60]]
[[ 36  65  60  66  84  82]
 [ 21  15  68  61  84  74]
 [ 79  24  65  27  47  17]
 [ 55  29  98  88  17  81]
 [ 91  10  38  41  96  55]
 [100  54  82  40  97  25]]


- Exercici 3

Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [4]:
def rowColumnsTotal(array): 
    
    if array.ndim!=2:
        print("Error: The array should be only two dimension")
        
    else:
        rows=np.sum(array, axis=1)
        col=np.sum(array, axis=0)
        print("Total of rows:", rows)
        print("Total of columns:", col)

rowColumnsTotal(arr2)

Total of rows: [3 8 9]
Total of columns: [11  9]


- Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [24]:
# (cov(X, Y)) / (std(X) * std(Y))

from numpy import random

X = [1, 2, 3, 4]
Y = [4, 5, 6, 7]

a = random.randint(100, size = (50))
b = random.randint(10, size = (50))
c = random.randint(10, size = (10))

def coef_Corr (X,Y):
    
    if len(X) != len(Y):
        
        print('Error: The dimension should be the same')
    else:
    
        cov = sum ((X[i] - np.mean(X)) * (Y[i] - np.mean(Y)) for i in range(len(X)))/(len(X)-1)

        stdX =(np.sum((X-np.mean(X))**2)/(len(X)-1))**(1/2)
        stdY =(np.sum((Y-np.mean(Y))**2)/(len(Y)-1))**(1/2)

        corr = cov / (stdX * stdY)

        return corr

print(coef_Corr (X,Y))

print(coef_Corr (a,b))

print(coef_Corr (a,c))

1.0000000000000002
-0.08935340609020616
Error: The dimension should be the same
None
